# -*- coding: utf-8 -*-
"""python_basics_Ganesh Maduri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKZNr0780jQAZ7lPCVaD4YhobGJdL3qK
"""

name=str(input("enter you name:"))
age=int(input("enter age:"))
height=float(input("enter height in meters:"))
is_student=input("Are you a student?(yes/no)")
print(name,age, height,is_student)

print(f"Name:{name} Age:{age} |Height:{height} |Student {is_student}")

print("age in month:",age*12)
print("age in days:",age*365)
print("Reminder:",age%7)
print("power of age:",age**2)

